# ==================
# Project Details
# ==================
name: "adventureworks"
config-version: 2
version: "1.0.0"
profile: "adventureworks"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_packages"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analyses"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Model Configs
# ==================
models:
  adventureworks:
    marts: {}
